### ISSUE TITLE
【バグ】顧客登録ユニットテストで、エラーメッセージの正当性を検証するテスト部分に、AssertionErrorが発生する

### ISSUE THREAD

**Issue by tetsunosuke** [tetsunosuke/paperwork-system#4]
https://github.com/iihama-h/paperwork-system/issues/5

再現する状況が異なるので要確認

**Comment by tetsunosuke** [comment]
```
tito@01-0343 paperwork_system % python manage.py test quotation.tests.test_RegistrationView.Test_QuotationRegistrationView.Test_create_quotation_failure_min_integer
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
2021-05-24 21:34:56,000	[ERROR]	/Users/tito/work/menta/madai/paperwork_system/quotation/views.py(Line:110)	Quotation could not be registered by Users.id:1
<QueryDict: {'quotation_id': ['6'], 'client_id': ['1'], 'expiry': [''], 'recipient': [''], 'title': [''], 'delivery_time': [''], 'delivery_location': [''], 'delivery_method': [''], 'payment_condition': [''], 'remark': [''], 'quotations_details_set-TOTAL_FORMS': ['1'], 'quotations_details_set-INITIAL_FORMS': ['0'], 'quotations_details_set-MIN_NUM_FORMS': ['0'], 'quotations_details_set-MAX_NUM_FORMS': ['1000'], 'quotations_details_set-0-merchandise': ['商品名'], 'quotations_details_set-0-merchandise_description': [''], 'quotations_details_set-0-quantity': ['-2147483649'], 'quotations_details_set-0-unit': [''], 'quotations_details_set-0-sales_unit_price': ['-2147483649'], 'quotations_details_set-0-purchase_unit_price': ['-2147483649'], 'file': ['']}>
F
======================================================================
FAIL: Test_create_quotation_failure_min_integer (quotation.tests.test_RegistrationView.Test_QuotationRegistrationView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tito/.pyenv/versions/3.8.2/lib/python3.8/site-packages/freezegun/api.py", line 778, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tito/work/menta/madai/paperwork_system/quotation/tests/test_RegistrationView.py", line 1775, in Test_create_quotation_failure_min_integer
    self.assertEqual(str(messages[0]), '登録ができませんでした。')
AssertionError: '顧客が存在しませんでした。' != '登録ができませんでした。'
- 顧客が存在しませんでした。
+ 登録ができませんでした。


----------------------------------------------------------------------
Ran 1 test in 0.415s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

Assertionエラーではあるが当初記載されている内容ではない。

**Comment by tetsunosuke** [comment]
```
    def form_invalid(self, form):
        logger.error(form.errors)
        try:
            if not Clients.objects.filter(
                    pk=self.request.POST.get('client_id')).exists():
                messages.error(self.request, '顧客が存在しませんでした。')
        except ValueError:
            messages.error(self.request, '顧客フィールドには顧客IDを入力してください。')

```

このようにして form.erros を出してみると

```
2021-05-24 21:34:56,000	[ERROR]	/Users/tito/work/menta/madai/paperwork_system/quotation/views.py(Line:111)	<ul class="errorlist"><li>client_id<ul class="errorlist"><li>正しく選択してください。選択したものは候補にありません。</li></ul></li></ul>
```

こうなります。入力の誤りはまずは form_invalidが呼ばれるので、その扱いが何か間違っているのでは？

**Comment by iihama-h** [comment]
問題が発生するテストメソッドは３つありますが、いずれも似たエラーになりますので、
一旦　Test_create_quotation_failure_min_integerメソッドで整理します。

1,　1927~1928行目
こちらはAssertメソッドの内容誤りでした。
誤：
        self.assertEqual(str(messages[0]), '顧客フィールドには顧客IDを入力してください。')
        self.assertEqual(str(messages[1]), '登録ができませんでした。')
正：
        self.assertEqual(str(messages[0]), '登録ができませんでした。')
        self.assertEqual(str(messages[1]), '顧客フィールドには顧客IDを入力してください。')

2,　本エラーの再現方法について、整理します。
・1769~1771行目のコメントアウトになっているAssertメソッドを外す
・1999行目　# sself.Test_create_quotation_failure_min_integer()　コメントアウトを外す
・「python manage.py test quotation.tests.test_RegistrationView」こちらのコマンドでテストを実行する
・以下のエラーが発生する

======================================================================
FAIL: test_create_quotation_ordering (quotation.tests.test_RegistrationView.Test_QuotationRegistrationView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\husah\Dropbox\見積システム\paperwork_system\quotation\tests\test_RegistrationView.py", line 1999, in test_create_quotation_ordering
    self.Test_create_quotation_failure_min_integer()
  File "C:\Users\husah\paperwork_system\lib\site-packages\freezegun\api.py", line 778, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\husah\Dropbox\見積システム\paperwork_system\quotation\tests\test_RegistrationView.py", line 1769, in Test_create_quotation_failure_min_integer
    self.assertFormsetError(response, 'Quotations_details_form', 0, 'quantity', 'この値は -2147483648 以上でなければなりません。')
  File "C:\Users\husah\paperwork_system\lib\site-packages\django\test\testcases.py", line 556, in assertFormsetError
    self.fail(msg_prefix + 'Response did not use any contexts to '
AssertionError: Response did not use any contexts to render the response

----------------------------------------------------------------------
Ran 1 test in 1.073s

FAILED (failures=1)
Destroying test database for alias 'default'...

**Comment by iihama-h** [comment]
気になる挙動があったため、共有します。

上記のテストを行った後に、以下の対応を行うと、今まで問題がなかったAsserメソッドでエラーが発生します。
・1769～1771行目（更新前　1742~1744行目）のコメントアウトを外したコードを改めて、コメントアウト化
・「python manage.py test quotation.tests.test_RegistrationView」こちらのコマンドでテストを実行する


```
======================================================================
FAIL: test_create_quotation_ordering (quotation.tests.test_RegistrationView.Test_QuotationRegistrationView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\husah\Dropbox\見積システム\paperwork_system\quotation\tests\test_RegistrationView.py", line 2002, in test_create_quotation_ordering
    self.Test_create_quotation_failure_not_client_id()
  File "C:\Users\husah\paperwork_system\lib\site-packages\freezegun\api.py", line 778, in wrapper
    result = func(*args, **kwargs)
  File "C:\Users\husah\Dropbox\見積システム\paperwork_system\quotation\tests\test_RegistrationView.py", line 1927, in Test_create_quotation_failure_not_client_id
    self.assertEqual(str(messages[0]), '顧客フィールドには顧客IDを入力してください。')
AssertionError: '登録ができませんでした。' != '顧客フィールドには顧客IDを入力してください。'
- 登録ができませんでした。
+ 顧客フィールドには顧客IDを入力してください。


----------------------------------------------------------------------
Ran 1 test in 1.068s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

なお、以下のように修正した場合、テストが通るようになります。
修正前：
        self.assertEqual(str(messages[0]), '顧客フィールドには顧客IDを入力してください。')
        self.assertEqual(str(messages[1]), '登録ができませんでした。')
修正後：
        self.assertEqual(str(messages[0]), '登録ができませんでした。')
        self.assertEqual(str(messages[1]), '顧客フィールドには顧客IDを入力してください。')

**Comment by tetsunosuke** [comment]
```
tito@01-0343 paperwork-system % python manage.py test quotation.tests.test_RegistrationView.Test_QuotationRegistrationView.Test_create_quotation_failure_min_integer
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
2021-05-24 21:34:56,000	[ERROR]	/Users/tito/work/menta/madai/origin/paperwork-system/quotation/views.py(Line:110)	Quotation could not be registered by Users.id:1
<QueryDict: {'quotation_id': ['6'], 'client_id': ['1'], 'expiry': [''], 'recipient': [''], 'title': [''], 'delivery_time': [''], 'delivery_location': [''], 'delivery_method': [''], 'payment_condition': [''], 'remark': [''], 'quotations_details_set-TOTAL_FORMS': ['1'], 'quotations_details_set-INITIAL_FORMS': ['0'], 'quotations_details_set-MIN_NUM_FORMS': ['0'], 'quotations_details_set-MAX_NUM_FORMS': ['1000'], 'quotations_details_set-0-merchandise': ['商品名'], 'quotations_details_set-0-merchandise_description': [''], 'quotations_details_set-0-quantity': ['-2147483649'], 'quotations_details_set-0-unit': [''], 'quotations_details_set-0-sales_unit_price': ['-2147483649'], 'quotations_details_set-0-purchase_unit_price': ['-2147483649'], 'file': ['']}>
F
======================================================================
FAIL: Test_create_quotation_failure_min_integer (quotation.tests.test_RegistrationView.Test_QuotationRegistrationView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/tito/.pyenv/versions/3.8.2/lib/python3.8/site-packages/freezegun/api.py", line 778, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tito/work/menta/madai/origin/paperwork-system/quotation/tests/test_RegistrationView.py", line 1769, in Test_create_quotation_failure_min_integer
    self.assertFormsetError(response, 'Quotations_details_form', 0, 'quantity', 'この値は -2147483648 以上でなければなりません。')
  File "/Users/tito/.pyenv/versions/3.8.2/lib/python3.8/site-packages/django/test/testcases.py", line 556, in assertFormsetError
    self.fail(msg_prefix + 'Response did not use any contexts to '
AssertionError: Response did not use any contexts to render the response

----------------------------------------------------------------------
Ran 1 test in 0.349s

FAILED (failures=1)
```

とりあえずorderingのテストでの実施はできるだけ避けたかったのですが、上記での再現が認められたのでこれはこれで問題ないかなと思いました。

この挙動は
details_formset.is_valid() が Falseになることで、
views.py の 100行目付近のelseに渡り、
その時点で
logger.info(details_formset.errors) すると、
```
[{'quantity': ['この値は -2147483648 以上でなければなりません。'], 'sales_unit_price': ['この値は -2147483648 以上でなければなりません。'], 'purchase_unit_price': ['この値は -2147483648 以上でなければなりません。']}]
```

を得ることができます。
したがってこのユニットテストにおいて formにdetails_formset のエラーを渡すような内容にしないとメッセージが取れない
と思います。（ちょっとやったことがないので調べる必要がありそう）

**Comment by iihama-h** [comment]
ご尽力いただき、ありがとうございます。　#2と共に問題解決が確認できました。

>AssertionError: Response did not use any contexts to render the response
が出るわけですが、これはリダイレクトされてしまうことによって何もRenderされないよという話なので、
ちょっとやりとりさかのぼりますと
         response = self.client.post(
             reverse_lazy('quotation:registration'), params, follow=True)
のようにしないとだめっぽいですね。


やはり、follow=True　の設定があってもなくてもテスト結果に影響なさそうでした。
調べてみましたが、follow=Trueの影響は、responseに格納される内容が、リダイレクト先まで含めるかどうかのようです。
本テスト内容は、Viewの処理内容をテストしているので、リダイレクト先の情報はあってもなくても変わらないのかなと考えています。。
（今回のmessagesのテストは、リダイレクトに関わらず、Viewでmessagesを生成している。）



>invalidにうまくデータを流していないのでエラーメッセージの表示がおかしかったというわけです。

こちらが主原因で間違いなさそうです。
Django のClassViewの仕様として、form_valid関数(またはform_invalid関数)には戻り値が必要だったということでしょうか。

・Test_create_quotation_failure_maxメソッド
これはform_valid関数(43行目)は呼ばれず、直接にform_invalid関数(113行目)が呼ばれていたため、form_invalid関数で正しい戻り値を返し、問題なく動いていた

・Test_create_quotation_failure_min_integerメソッド
form_valid関数からform_invalid関数を呼んでおり（110行目）、ここで正しくform_valid関数としての戻り値を返していないため、挙動が不正だった




今回のバグはDjangoの仕様的な問題（DjangoのClassViewの仕様を正しく知らなかったことによるバグ混入）だったと思っています。
本件、どのようにバグの把握をされましたでしょうか。（戻り値が必要な仕様を、既にご存じだったのでしょうか？）
今回、Djangoでシステムを作成してみて、Djangoに関して詳細な情報が少ないことがかなり難点になったと思っています。
（公式ドキュメントにも記載されていない仕様が、結構あるような）
本件、自分自身で問題解決まで至れるよう、アドバイスいただけますと幸いです。

**Comment by tetsunosuke** [comment]
@iihama-h 

> やはり、follow=True　の設定があってもなくてもテスト結果に影響なさそうでした。

なるほど、そうだったんですね。実際にレンダリングしているコンテンツとの関係があると思っていたんですがそうではなかったのですか。誤解してました。

> Django のClassViewの仕様として、form_valid関数(またはform_invalid関数)には戻り値が必要だったということでしょうか。

ここはそうです、とも言えるのですがちょっと誤解があるようです。
```
             return self.form_invalid(form)
        return super().form_valid(form)
```

この状態がもし

```
            self.form_invalid(form)
        return super().form_valid(form)
```

このままですと、最終的に return されるのは super().form_valid(form) ですよね。
なのでフォームが正常完了しているのと同じ挙動になってしまっているということです（そのためトランザクションが正常完了してしまう）
結果論ではありますが凡ミスです。

> 今回のバグはDjangoの仕様的な問題（DjangoのClassViewの仕様を正しく知らなかったことによるバグ混入）だったと思っています。
> 本件、どのようにバグの把握をされましたでしょうか。（戻り値が必要な仕様を、既にご存じだったのでしょうか？）
> 今回、Djangoでシステムを作成してみて、Djangoに関して詳細な情報が少ないことがかなり難点になったと思っています。
>（公式ドキュメントにも記載されていない仕様が、結構あるような）

まあ確かにそこはそんな気がしますね。
仕様については十分把握できていなかったのですが、responseとして返ってくるはずのオブジェクトの中身について、正常時と異常時の違いを見ていました。
その結果正常なときと異常なときの中身が違っていて
（それでresponseを取るときにfollow=Trueした上でcontentとかを参照してエラーメッセージが正しく表示されているのかを見ているときに差分に気づいて検証しました）

**Comment by tetsunosuke** [comment]
クローズ連絡いただいているので閉じます
